#!/usr/bin/env fish

set -x WP_HOST 192.168.56.101
set -x WP_USER andrew
set -x WP_PASS 1234abcd
set -x WP_RESET_PATH wordpress.sql

# Generate reset sql given IP of target
rm $WP_RESET_PATH
nix-build wordpress.sql.nix --argstr ip $WP_HOST -o $WP_RESET_PATH

ghci
